#ifndef _ALTERA_NIOS2_GEN2_0_H_
#define _ALTERA_NIOS2_GEN2_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'nios2_gen2_0' and devices
 * connected to the following masters:
 *   data_master
 *   instruction_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for module 'nios2_gen2_0', class 'altera_nios2_gen2'.
 * The macros have no prefix.
 */
#define BIG_ENDIAN 0
#define BREAK_ADDR 0x10020
#define CPU_ARCH_NIOS2_R1 
#define CPU_FREQ 50000000
#define CPU_ID_SIZE 1
#define CPU_ID_VALUE 0x00000000
#define CPU_IMPLEMENTATION "tiny"
#define DATA_ADDR_WIDTH 17
#define DCACHE_LINE_SIZE 0
#define DCACHE_LINE_SIZE_LOG2 0
#define DCACHE_SIZE 0
#define EXCEPTION_ADDR 0x20
#define FLASH_ACCELERATOR_LINES 0
#define FLASH_ACCELERATOR_LINE_SIZE 0
#define FLUSHDA_SUPPORTED 
#define HARDWARE_DIVIDE_PRESENT 0
#define HARDWARE_MULTIPLY_PRESENT 0
#define HARDWARE_MULX_PRESENT 0
#define HAS_DEBUG_CORE 1
#define HAS_DEBUG_STUB 
#define HAS_ILLEGAL_INSTRUCTION_EXCEPTION 
#define HAS_JMPI_INSTRUCTION 
#define ICACHE_LINE_SIZE 0
#define ICACHE_LINE_SIZE_LOG2 0
#define ICACHE_SIZE 0
#define INST_ADDR_WIDTH 17
#define OCI_VERSION 1
#define RESET_ADDR 0x0

/*
 * Macros for device 'ocram_64K', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'OCRAM_64K_'.
 * The prefix is the slave descriptor.
 */
#define OCRAM_64K_COMPONENT_TYPE altera_avalon_onchip_memory2
#define OCRAM_64K_COMPONENT_NAME ocram_64K
#define OCRAM_64K_BASE 0x0
#define OCRAM_64K_SPAN 65536
#define OCRAM_64K_END 0xffff
#define OCRAM_64K_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define OCRAM_64K_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define OCRAM_64K_CONTENTS_INFO ""
#define OCRAM_64K_DUAL_PORT 0
#define OCRAM_64K_GUI_RAM_BLOCK_TYPE AUTO
#define OCRAM_64K_INIT_CONTENTS_FILE soc_system_ocram_64K
#define OCRAM_64K_INIT_MEM_CONTENT 1
#define OCRAM_64K_INSTANCE_ID NONE
#define OCRAM_64K_NON_DEFAULT_INIT_FILE_ENABLED 0
#define OCRAM_64K_RAM_BLOCK_TYPE AUTO
#define OCRAM_64K_READ_DURING_WRITE_MODE DONT_CARE
#define OCRAM_64K_SINGLE_CLOCK_OP 0
#define OCRAM_64K_SIZE_MULTIPLE 1
#define OCRAM_64K_SIZE_VALUE 65536
#define OCRAM_64K_WRITABLE 1
#define OCRAM_64K_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define OCRAM_64K_MEMORY_INFO_GENERATE_DAT_SYM 1
#define OCRAM_64K_MEMORY_INFO_GENERATE_HEX 1
#define OCRAM_64K_MEMORY_INFO_HAS_BYTE_LANE 0
#define OCRAM_64K_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define OCRAM_64K_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define OCRAM_64K_MEMORY_INFO_MEM_INIT_FILENAME soc_system_ocram_64K

/*
 * Macros for device 'switch_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'SWITCH_PIO_'.
 * The prefix is the slave descriptor.
 */
#define SWITCH_PIO_COMPONENT_TYPE altera_avalon_pio
#define SWITCH_PIO_COMPONENT_NAME switch_pio
#define SWITCH_PIO_BASE 0x10800
#define SWITCH_PIO_SPAN 16
#define SWITCH_PIO_END 0x1080f
#define SWITCH_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define SWITCH_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SWITCH_PIO_CAPTURE 0
#define SWITCH_PIO_DATA_WIDTH 3
#define SWITCH_PIO_DO_TEST_BENCH_WIRING 0
#define SWITCH_PIO_DRIVEN_SIM_VALUE 0
#define SWITCH_PIO_EDGE_TYPE NONE
#define SWITCH_PIO_FREQ 50000000
#define SWITCH_PIO_HAS_IN 1
#define SWITCH_PIO_HAS_OUT 0
#define SWITCH_PIO_HAS_TRI 0
#define SWITCH_PIO_IRQ_TYPE NONE
#define SWITCH_PIO_RESET_VALUE 0

/*
 * Macros for device 'button_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'BUTTON_PIO_'.
 * The prefix is the slave descriptor.
 */
#define BUTTON_PIO_COMPONENT_TYPE altera_avalon_pio
#define BUTTON_PIO_COMPONENT_NAME button_pio
#define BUTTON_PIO_BASE 0x10810
#define BUTTON_PIO_SPAN 16
#define BUTTON_PIO_END 0x1081f
#define BUTTON_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define BUTTON_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BUTTON_PIO_CAPTURE 0
#define BUTTON_PIO_DATA_WIDTH 4
#define BUTTON_PIO_DO_TEST_BENCH_WIRING 0
#define BUTTON_PIO_DRIVEN_SIM_VALUE 0
#define BUTTON_PIO_EDGE_TYPE NONE
#define BUTTON_PIO_FREQ 50000000
#define BUTTON_PIO_HAS_IN 1
#define BUTTON_PIO_HAS_OUT 0
#define BUTTON_PIO_HAS_TRI 0
#define BUTTON_PIO_IRQ_TYPE NONE
#define BUTTON_PIO_RESET_VALUE 0

/*
 * Macros for device 'led_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'LED_PIO_'.
 * The prefix is the slave descriptor.
 */
#define LED_PIO_COMPONENT_TYPE altera_avalon_pio
#define LED_PIO_COMPONENT_NAME led_pio
#define LED_PIO_BASE 0x10820
#define LED_PIO_SPAN 16
#define LED_PIO_END 0x1082f
#define LED_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define LED_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LED_PIO_CAPTURE 0
#define LED_PIO_DATA_WIDTH 4
#define LED_PIO_DO_TEST_BENCH_WIRING 0
#define LED_PIO_DRIVEN_SIM_VALUE 0
#define LED_PIO_EDGE_TYPE NONE
#define LED_PIO_FREQ 50000000
#define LED_PIO_HAS_IN 0
#define LED_PIO_HAS_OUT 1
#define LED_PIO_HAS_TRI 0
#define LED_PIO_IRQ_TYPE NONE
#define LED_PIO_RESET_VALUE 0

/*
 * Macros for device 'sysid_qsys_0', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_0_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_0_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_0_COMPONENT_NAME sysid_qsys_0
#define SYSID_QSYS_0_BASE 0x10830
#define SYSID_QSYS_0_SPAN 8
#define SYSID_QSYS_0_END 0x10837
#define SYSID_QSYS_0_ID 3725647376
#define SYSID_QSYS_0_TIMESTAMP 1616564416

/*
 * Macros for device 'jtag_uart_0', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_0_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_0_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_0_COMPONENT_NAME jtag_uart_0
#define JTAG_UART_0_BASE 0x10838
#define JTAG_UART_0_SPAN 8
#define JTAG_UART_0_END 0x1083f
#define JTAG_UART_0_IRQ 0
#define JTAG_UART_0_READ_DEPTH 64
#define JTAG_UART_0_READ_THRESHOLD 8
#define JTAG_UART_0_WRITE_DEPTH 64
#define JTAG_UART_0_WRITE_THRESHOLD 8


#endif /* _ALTERA_NIOS2_GEN2_0_H_ */
